I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 679, in script
    if menu_flag1 == False:
  File "game/script.rpy", line 679, in <module>
    if menu_flag1 == False:
NameError: name 'menu_flag1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 679, in script
    if menu_flag1 == False:
  File "D:\Program Files\renpy-8.1.0-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "D:\Program Files\renpy-8.1.0-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Program Files\renpy-8.1.0-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 679, in <module>
    if menu_flag1 == False:
NameError: name 'menu_flag1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.0.23051307
A Feudal Feud 1.0
Tue May 16 17:56:16 2023
